"""Exact public platform policies, independent ownership and asset metadata.

No channel identity, video subject or speaker is inferred from collected names.
"""
from __future__ import annotations

import re
from datetime import datetime
from urllib.parse import parse_qsl, urlsplit

from czlake.production_budget import digest

YOUTUBE = "streamers/youtube-scraper"
X = "apidojo/twitter-scraper-lite"
TIKTOK = "clockworks/tiktok-scraper"
NEW_ACTORS = {YOUTUBE, X, TIKTOK}
PRICE_UNITS = {YOUTUBE: "Video", X: "Dataset Item Tier 1", TIKTOK: "Result"}
PLATFORM_HOSTS = {"youtube": {"youtube.com", "www.youtube.com", "youtu.be"}, "x": {"x.com", "www.x.com", "twitter.com", "www.twitter.com"}, "tiktok": {"tiktok.com", "www.tiktok.com"}}
YOUTUBE_FIELDS = {
    "id", "type", "title", "text", "url", "inputUrl", "input", "inputChannelUrl", "fromYTUrl", "fromChannelListPage", "description", "duration", "date",
    "publishedAt", "uploadedAt", "viewCount", "likes", "likeCount", "commentsCount",
    "numberOfSubscribers", "channelId", "channelName", "channelUrl", "channelUsername",
    "channelDescription", "channelJoinedDate", "channelTotalViews", "channelTotalVideos", "channelAvatarUrl", "channelBannerUrl", "isChannelVerified", "thumbnailUrl",
    "thumbnail", "isShort", "isLive", "isLiveContent", "ageRestricted",
    "isMembersOnly", "isPaidContent", "isAgeRestricted", "commentsTurnedOff", "isPrivate", "isUnlisted", "availability", "error", "errorCode",
}
DISABLED_YOUTUBE = {
    "transcriptionAndSubtitle": "NONE", "aiVideoDescription": False,
    "aiVideoSummary": False, "saveSubsToKVS": False,
    "preferAutoGeneratedSubtitles": False,
}

DISABLED_TIKTOK = {
    "excludePinnedPosts": False, "maxFollowersPerProfile": 0,
    "maxFollowingPerProfile": 0, "commentsPerPost": 0,
    "topLevelCommentsPerPost": 0, "maxRepliesPerComment": 0,
    "shouldDownloadVideos": False, "shouldDownloadCovers": False,
    "shouldDownloadSlideshowImages": False, "shouldDownloadAvatars": False,
    "shouldDownloadMusicCovers": False, "scrapeRelatedVideos": False,
    "scrapeRelatedSearchWords": False, "scrapeAdditionalAuthorMeta": False,
    "aiVideoDescription": False, "aiVideoSummary": False,
    "downloadSubtitlesOptions": "NEVER_DOWNLOAD_SUBTITLES", "proxyCountryCode": "None",
}
X_QUERY = re.compile(r"from:([A-Za-z0-9_]{1,15}) filter:media -filter:replies -filter:retweets")
X_FIELDS = {
    "id", "url", "twitterUrl", "createdAt", "text", "fullText", "lang",
    "isReply", "isRetweet", "isQuote", "isPinned", "likeCount", "quoteCount",
    "replyCount", "retweetCount", "viewCount", "bookmarkCount", "errorCode",
}
X_AUTHOR_FIELDS = {
    "id", "userName", "name", "twitterUrl", "url", "profilePicture",
    "coverPicture", "protected", "followers", "following", "mediaCount",
    "statusesCount", "isVerified", "isBlueVerified", "createdAt",
}
TIKTOK_FIELDS = {
    "id", "webVideoUrl", "text", "createTime", "createTimeISO", "diggCount",
    "playCount", "shareCount", "commentCount", "collectCount", "repostCount",
    "isSlideshow", "isPinned", "isStory", "input", "fromProfileSection", "errorCode",
}
TIKTOK_AUTHOR_FIELDS = {
    "id", "name", "nickName", "profileUrl", "privateAccount", "avatar",
    "originalAvatarUrl", "verified", "fans", "following", "heart", "video",
}


def validate_x_input(run_input, max_items, bounded_int):
    if set(run_input) != {"searchTerms", "sort", "maxItems", "includeSearchTerms"}:
        raise ValueError("Only the reviewed media-search X input is allowed")
    if run_input["sort"] != "Latest" or run_input["includeSearchTerms"] is not True:
        raise ValueError("X requires Latest and retained exact search terms")
    if bounded_int(run_input["maxItems"], 1, 10000, "maxItems") != max_items:
        raise ValueError("X global maxItems differs from reserved maximum")
    terms = run_input["searchTerms"]
    if not isinstance(terms, list) or not 1 <= len(terms) <= 5:
        raise ValueError("X Tier 1 permits one to five bounded queries")
    handles = []
    for term in terms:
        match = X_QUERY.fullmatch(term) if isinstance(term, str) else None
        if match is None:
            raise ValueError("X query must target one exact publisher, excluding replies and reposts")
        handles.append(match[1].lower())
    if len(set(handles)) != len(handles):
        raise ValueError("Duplicate X publisher queries")


def validate_tiktok_input(run_input, max_items, bounded_int):
    if set(run_input) != {"profiles", "resultsPerPage", "profileScrapeSections", "profileSorting", *DISABLED_TIKTOK}:
        raise ValueError("Only the reviewed profiles/videos TikTok input is allowed")
    for key, value in DISABLED_TIKTOK.items():
        if type(run_input[key]) is not type(value) or run_input[key] != value:
            raise ValueError("TikTok extras must be explicitly disabled")
    if run_input["profileScrapeSections"] != ["videos"] or run_input["profileSorting"] != "latest":
        raise ValueError("Only latest profile videos are allowed")
    profiles = run_input["profiles"]
    if (not isinstance(profiles, list) or not 1 <= len(profiles) <= 20
            or any(not isinstance(p, str) or not re.fullmatch(r"[A-Za-z0-9_.]{1,24}", p) for p in profiles)
            or len({p.lower() for p in profiles}) != len(profiles)):
        raise ValueError("Exact distinct TikTok profiles required")
    limit = bounded_int(run_input["resultsPerPage"], 1, max_items, "resultsPerPage")
    if limit * len(profiles) > max_items:
        raise ValueError("TikTok per-profile limits exceed reserved total")


def social_profile_url(platform, value):
    if platform not in {"x", "tiktok"} or not isinstance(value, str):
        raise ValueError("Exact social profile URL required")
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or parsed.hostname not in PLATFORM_HOSTS[platform]
            or parsed.username or parsed.password or parsed.port is not None or parsed.query or parsed.fragment):
        raise ValueError("Invalid exact public social profile URL")
    pattern = r"/([A-Za-z0-9_]{1,15})/?" if platform == "x" else r"/@([A-Za-z0-9_.]{1,24})/?"
    match = re.fullmatch(pattern, parsed.path)
    if not match or match[1].lower() in {"home", "explore", "search", "settings", "login", "intent", "i"}:
        raise ValueError("Unsupported social profile path")
    return "profile", match[1].lower()


def source_input(envelope):
    """Input provenance for strict new lanes; legacy YouTube may omit it."""
    value = envelope.get("collection_input")
    if envelope.get("actor") in {X, TIKTOK}:
        if not isinstance(value, dict) or digest(value) != envelope.get("input_sha256"):
            raise ValueError("New social source lacks exact collection input provenance")
    return value


def _objects(value, maximum=1000):
    if not isinstance(value, list) or len(value) > maximum or any(not isinstance(v, dict) for v in value):
        raise ValueError("Unexpected public media object list")
    return value


def _strings(value, maximum=1000):
    if (not isinstance(value, list) or len(value) > maximum
            or any(not isinstance(v, str) or len(v) > 4096 for v in value)):
        raise ValueError("Unexpected public media string list")
    return value


def x_metadata(item, scalar_fields):
    result = scalar_fields(item, X_FIELDS)
    if isinstance(item.get("author"), dict):
        result["author"] = scalar_fields(item["author"], X_AUTHOR_FIELDS)
    for key in ("media", "searchTerms"):
        if key in item:
            result[key] = _strings(item[key], 100 if key == "media" else 5)
    if "videos" in item:
        result["videos"] = []
        for source in _objects(item["videos"], 100):
            video = scalar_fields(source, {"durationMillis"})
            if "variants" in source:
                video["variants"] = [scalar_fields(v, {"bitrate", "contentType", "url"}) for v in _objects(source["variants"], 30)]
            result["videos"].append(video)
    for group in ("entities", "extendedEntities"):
        source = item.get(group)
        if not isinstance(source, dict) or "media" not in source:
            continue
        result[group] = {"media": []}
        for value in _objects(source["media"], 100):
            media = scalar_fields(value, {"media_url_https", "expanded_url", "type", "id_str"})
            info = value.get("video_info")
            if isinstance(info, dict) and "variants" in info:
                media["video_info"] = {"variants": [scalar_fields(v, {"url", "content_type", "bitrate"}) for v in _objects(info["variants"], 30)]}
            result[group]["media"].append(media)
    return result


def tiktok_metadata(item, scalar_fields):
    result = scalar_fields(item, TIKTOK_FIELDS)
    if isinstance(item.get("authorMeta"), dict):
        result["authorMeta"] = scalar_fields(item["authorMeta"], TIKTOK_AUTHOR_FIELDS)
    if isinstance(item.get("videoMeta"), dict):
        result["videoMeta"] = scalar_fields(item["videoMeta"], {"duration", "width", "height", "coverUrl", "originalCoverUrl", "downloadAddr"})
    if "slideshowImageLinks" in item:
        result["slideshowImageLinks"] = [scalar_fields(v, {"downloadLink", "tiktokLink"}) for v in _objects(item["slideshowImageLinks"], 100)]
    return result


def _public_post_url(platform, value, owner, raw_id):
    if not isinstance(value, str):
        raise ValueError("Public post requires an exact source URL")
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or parsed.hostname not in PLATFORM_HOSTS[platform]
            or parsed.username or parsed.password or parsed.port is not None or parsed.query or parsed.fragment):
        raise ValueError("Invalid public post URL")
    pattern = r"/([A-Za-z0-9_]{1,15})/status/([0-9]{1,30})/?" if platform == "x" else r"/@([A-Za-z0-9_.]{1,24})/(?:video|photo)/([0-9]{1,30})/?"
    match = re.fullmatch(pattern, parsed.path)
    if match is None or match[1].lower() != owner or match[2] != raw_id:
        raise ValueError("Returned publisher/id differs from public post URL")
    return value


def normalize_x_asset(record, run_input):
    author = record.get("author", {})
    if (not isinstance(author, dict) or author.get("protected") is not False
            or record.get("isReply") is not False or record.get("isRetweet") is not False or record.get("errorCode")):
        raise ValueError("Public original X publisher flags are required")
    owner = account_identity("x", author.get("userName"))
    raw_id = record.get("id")
    terms = run_input.get("searchTerms", []) if isinstance(run_input, dict) else []
    handles = {m[1].lower() for value in terms if isinstance(value, str) and (m := X_QUERY.fullmatch(value))}
    if owner not in handles or not isinstance(raw_id, str) or not re.fullmatch(r"[0-9]{1,30}", raw_id):
        raise ValueError("X publisher must match one exact collected target")
    public = _public_post_url("x", record.get("url") or record.get("twitterUrl"), owner, raw_id)
    owner_url = author.get("twitterUrl")
    if owner_url is not None and social_profile_url("x", owner_url)[1] != owner:
        raise ValueError("X author profile identity mismatch")
    text = record.get("fullText") if record.get("fullText") is not None else record.get("text")
    if text is not None and not isinstance(text, str):
        raise ValueError("X text must be scalar")
    fields = new_media_fields(X, record, "")
    published = record.get("createdAt")
    if isinstance(published, str):
        try:
            published = datetime.strptime(published, "%a %b %d %H:%M:%S %z %Y").isoformat()
        except ValueError:
            pass  # ISO dates are subsequently checked by the common ingest parser.
    return dict(platform="x", lane="x_public_post", raw_id=raw_id, text=text, owner=owner,
                owner_url=owner_url or "https://x.com/" + owner, public_source=public,
                published_at=published, kind="Post",
                preview=next((v for k, v, _ in fields if k == "image"), None),
                video=next((v for k, v, _ in fields if k == "video"), None),
                values={"likes": record.get("likeCount"), "views": record.get("viewCount"), "comments_count": record.get("replyCount"), "shares": record.get("retweetCount")})


def normalize_tiktok_asset(record, run_input):
    author = record.get("authorMeta", {})
    if (not isinstance(author, dict) or author.get("privateAccount") is not False
            or record.get("isStory") is True or record.get("errorCode")):
        raise ValueError("Explicit public TikTok author required")
    owner = account_identity("tiktok", author.get("name"))
    raw_id = record.get("id")
    profiles = run_input.get("profiles", []) if isinstance(run_input, dict) else []
    if (owner not in {p.lower() for p in profiles if isinstance(p, str)}
            or not isinstance(raw_id, str) or not re.fullmatch(r"[0-9]{1,30}", raw_id)):
        raise ValueError("TikTok publisher must match one exact collected profile")
    public = _public_post_url("tiktok", record.get("webVideoUrl"), owner, raw_id)
    owner_url = author.get("profileUrl")
    if owner_url is not None and social_profile_url("tiktok", owner_url)[1] != owner:
        raise ValueError("TikTok author profile identity mismatch")
    text = record.get("text")
    if text is not None and not isinstance(text, str):
        raise ValueError("TikTok text must be scalar")
    fields = new_media_fields(TIKTOK, record, "")
    return dict(platform="tiktok", lane="tiktok_public_video", raw_id=raw_id, text=text, owner=owner,
                owner_url=owner_url or "https://www.tiktok.com/@" + owner, public_source=public,
                published_at=record.get("createTimeISO") or record.get("createTime"),
                kind="Image" if record.get("isSlideshow") is True else "Video",
                preview=next((v for k, v, _ in fields if k == "image"), None),
                video=next((v for k, v, _ in fields if k == "video"), None),
                values={"likes": record.get("diggCount"), "views": record.get("playCount"), "comments_count": record.get("commentCount"), "shares": record.get("shareCount")})


def youtube_url(value, *, profile_only=False):
    """Return exact channel identifier or video ID; reject open collection lanes."""
    if not isinstance(value, str) or len(value) > 2048:
        raise ValueError("An exact bounded YouTube HTTPS URL is required")
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or parsed.hostname not in PLATFORM_HOSTS["youtube"]
            or parsed.username or parsed.password or parsed.port is not None or parsed.fragment):
        raise ValueError("Invalid public YouTube host, credentials, port or fragment")
    if not profile_only:
        if parsed.hostname == "youtu.be" and re.fullmatch(r"/[A-Za-z0-9_-]{11}/?", parsed.path) and not parsed.query:
            return "video", parsed.path.strip("/")
        query = parse_qsl(parsed.query, keep_blank_values=True)
        if parsed.path == "/watch" and len(query) == 1 and query[0][0] == "v" and re.fullmatch(r"[A-Za-z0-9_-]{11}", query[0][1]):
            return "video", query[0][1]
        match = re.fullmatch(r"/(?:shorts|live)/([A-Za-z0-9_-]{11})/?", parsed.path)
        if match and not parsed.query:
            return "video", match[1]
    if parsed.hostname == "youtu.be" or parsed.query:
        raise ValueError("Unsupported public YouTube query or profile host")
    match = re.fullmatch(r"/(@[A-Za-z0-9_.-]{1,100}|channel/UC[A-Za-z0-9_-]{22}|(?:c|user)/[A-Za-z0-9_.-]{1,100})(?:/(?:videos|shorts|streams))?/?", parsed.path)
    if not match:
        raise ValueError("Only exact YouTube channel or video URLs are allowed")
    return "channel", match[1]


def validate_new_input(actor, run_input, max_items, bounded_int):
    if actor == X:
        return validate_x_input(run_input, max_items, bounded_int)
    if actor == TIKTOK:
        return validate_tiktok_input(run_input, max_items, bounded_int)
    if actor != YOUTUBE:
        raise ValueError("Unknown new-platform actor")
    allowed = {"startUrls", "maxResults", "maxResultsShorts", "maxResultStreams", "sortVideosBy", *DISABLED_YOUTUBE}
    if set(run_input) != allowed:
        raise ValueError("Only the exact reviewed YouTube fields are allowed")
    for key, disabled in DISABLED_YOUTUBE.items():
        if type(run_input.get(key)) is not type(disabled) or run_input[key] != disabled:
            raise ValueError("YouTube transcript/subtitle/AI extras must be explicitly disabled")
    if run_input["sortVideosBy"] not in {"NEWEST", "POPULAR", "OLDEST"}:
        raise ValueError("Invalid reviewed YouTube sorting")
    urls = run_input["startUrls"]
    if not isinstance(urls, list) or not 1 <= len(urls) <= max_items:
        raise ValueError("Bounded exact public YouTube start URLs are required")
    limits = [bounded_int(run_input[key], 0, max_items, key) for key in ("maxResults", "maxResultsShorts", "maxResultStreams")]
    if not sum(limits):
        raise ValueError("A positive bounded YouTube result limit is required")
    identities, total = set(), 0
    for item in urls:
        if not isinstance(item, dict) or set(item) != {"url"}:
            raise ValueError("Only exact startUrls.url objects are allowed")
        identity = youtube_url(item["url"])
        if identity in identities:
            raise ValueError("Duplicate YouTube source identity")
        identities.add(identity)
        total += 1 if identity[0] == "video" else sum(limits)
    if total > max_items:
        raise ValueError("YouTube per-source result limits exceed global max_items")


def new_metadata(actor, item, scalar_fields):
    if actor == X:
        return x_metadata(item, scalar_fields)
    if actor == TIKTOK:
        return tiktok_metadata(item, scalar_fields)
    if actor != YOUTUBE:
        raise ValueError("Unknown new-platform output policy")
    return scalar_fields(item, YOUTUBE_FIELDS)


def account_identity(platform, value):
    if platform in {"x", "tiktok"} and isinstance(value, str):
        cleaned = value.lower().lstrip("@")
        pattern = r"[a-z0-9_]{1,15}" if platform == "x" else r"[a-z0-9_.]{1,24}"
        return cleaned if re.fullmatch(pattern, cleaned) else None
    if platform == "youtube" and isinstance(value, str):
        if re.fullmatch(r"(?:channel/UC[A-Za-z0-9_-]{22}|(?:c|user)/[A-Za-z0-9_.-]{1,100})", value):
            return value
        cleaned = value.lstrip("@").lower()
        if re.fullmatch(r"[a-z0-9_.-]{1,100}", cleaned):
            return "@" + cleaned
    return None


def independent_new_owner(proof, entity, as_of, platform):
    try:
        kind, identity = (youtube_url(proof.get("profile_url"), profile_only=True) if platform == "youtube" else social_profile_url(platform, proof.get("profile_url")))
        anchor = urlsplit(proof.get("source_url", ""))
        observed = datetime.fromisoformat(proof["observed_at"].replace("Z", "+00:00"))
        age = (datetime.fromisoformat(as_of.replace("Z", "+00:00")) - observed).total_seconds()
        expected = account_identity(platform, proof.get("handle"))
        actual = account_identity(platform, identity)
        accepted = all((platform in PLATFORM_HOSTS, entity is not None,
                        proof.get("adjudication") == "confirmed", proof.get("identity_confirmed") is True,
                        proof.get("anchor_links_account") is True, proof.get("public") is True,
                        anchor.scheme == "https", bool(anchor.hostname), not anchor.username, not anchor.password,
                        anchor.hostname not in {"instagram.com", "www.instagram.com", "facebook.com", "www.facebook.com", *(host for hosts in PLATFORM_HOSTS.values() for host in hosts)},
                        0 <= age <= 30 * 86400, actual is not None, actual == expected))
        if entity and entity.get("kind") == "local_list":
            accepted = accepted and proof.get("scope") == "city_political_organization" and str(proof.get("list_no")) == entity["entity_id"].split(":")[-1]
    except (ValueError, TypeError, KeyError, AttributeError):
        accepted = False
    return accepted, "independent_exact_anchor_confirmed" if accepted else "independent_exact_account_anchor_not_confirmed"


def normalize_new_asset(actor, record, run_input=None):
    if actor == X:
        return normalize_x_asset(record, run_input)
    if actor == TIKTOK:
        return normalize_tiktok_asset(record, run_input)
    if actor != YOUTUBE:
        raise ValueError("Unknown new-platform ingest policy")
    if (record.get("error") or record.get("errorCode") or record.get("isPrivate") is True
            or record.get("isMembersOnly") is True or record.get("isPaidContent") is True or record.get("isUnlisted") is True
            or record.get("availability") in {"private", "unavailable", "members_only", "login_required"}):
        raise ValueError("YouTube private/member/unavailable/error content is not a public asset")
    kind, video_id = youtube_url(record.get("url"))
    if kind != "video" or record.get("id") != video_id:
        raise ValueError("YouTube video ID differs from its exact public URL")
    owner, owner_url = None, None
    if isinstance(record.get("channelUrl"), str):
        _, channel = youtube_url(record["channelUrl"], profile_only=True)
        owner, owner_url = account_identity("youtube", channel), record["channelUrl"]
    title, description = record.get("title"), record.get("text") if record.get("text") is not None else record.get("description")
    if any(v is not None and not isinstance(v, str) for v in (title, description)):
        raise ValueError("YouTube title/description must be scalar text")
    return {
        "platform": "youtube", "lane": "youtube_public_video", "raw_id": video_id,
        "text": "\n\n".join(v for v in (title, description) if isinstance(v, str)) or None,
        "owner": owner, "owner_url": owner_url, "public_source": record["url"],
        "published_at": record.get("date") or record.get("publishedAt") or record.get("uploadedAt"),
        "kind": "Video", "preview": record.get("thumbnailUrl") or record.get("thumbnail"),
        "video": None, "values": {"likes": record.get("likes") if record.get("likes") is not None else record.get("likeCount"), "views": record.get("viewCount"), "comments_count": record.get("commentsCount"), "shares": None},
    }


def allowed_new_media_url(value, platform=None):
    if not isinstance(value, str):
        return False
    try:
        parsed = urlsplit(value)
        if parsed.scheme != "https" or parsed.port not in (None, 443) or parsed.username or parsed.password:
            return False
        host = parsed.hostname or ""
        if platform in (None, "youtube") and host in {"i.ytimg.com", "img.youtube.com"}:
            return True
        if platform in (None, "x") and host in {"pbs.twimg.com", "video.twimg.com"}:
            return True
        if platform in (None, "tiktok") and any(host.endswith("." + domain) for domain in ("tiktokcdn.com", "tiktokcdn-us.com", "byteoversea.com", "ibytedtos.com")):
            return True
    except ValueError:
        pass
    return False


def new_media_fields(actor, record, prefix):
    if actor == YOUTUBE:
        return [("image", record[key], prefix + "/" + key) for key in ("thumbnailUrl", "thumbnail") if isinstance(record.get(key), str)]
    if actor == TIKTOK:
        video = record.get("videoMeta", {})
        values = [("image", video[key], prefix + "/videoMeta/" + key) for key in ("coverUrl", "originalCoverUrl") if isinstance(video.get(key), str)]
        if isinstance(video.get("downloadAddr"), str):
            values.append(("video", video["downloadAddr"], prefix + "/videoMeta/downloadAddr"))
        for index, item in enumerate(record.get("slideshowImageLinks", [])):
            for key in ("downloadLink", "tiktokLink"):
                if isinstance(item.get(key), str):
                    values.append(("image", item[key], prefix + f"/slideshowImageLinks/{index}/{key}"))
        return values
    values = [("image", value, prefix + f"/media/{index}") for index, value in enumerate(record.get("media", [])) if isinstance(value, str)]
    for index, video in enumerate(record.get("videos", [])):
        values.extend(("video", variant["url"], prefix + f"/videos/{index}/variants/{j}/url") for j, variant in enumerate(video.get("variants", [])) if variant.get("contentType") == "video/mp4" and isinstance(variant.get("url"), str))
    for group in ("entities", "extendedEntities"):
        for index, media in enumerate(record.get(group, {}).get("media", [])):
            if isinstance(media.get("media_url_https"), str):
                values.append(("image", media["media_url_https"], prefix + f"/{group}/media/{index}/media_url_https"))
            values.extend(("video", variant["url"], prefix + f"/{group}/media/{index}/video_info/variants/{j}/url") for j, variant in enumerate(media.get("video_info", {}).get("variants", [])) if variant.get("content_type") == "video/mp4" and isinstance(variant.get("url"), str))
    return values


def validate_new_media_entry(actor, record, prefix, entry, run_input=None):
    normalized = normalize_new_asset(actor, record, run_input)
    expected = (entry["kind"], entry["url"], entry.get("source_media_pointer"))
    if (entry["asset_id"] != normalized["platform"] + ":" + normalized["raw_id"]
            or expected not in new_media_fields(actor, record, prefix)
            or not allowed_new_media_url(entry["url"], normalized["platform"])):
        raise ValueError("Public media differs from its exact source asset/field")
